GlobalFishingWatch/pipe-tools

- pipe_tools/cookbook/runall.sh
- pipe_tools/cookbook/schema_autodetect.py
- pipe_tools/io/bigquery.py
- pipe_tools/io/datepartitionedsink.py
- pipe_tools/transforms/util.py
> Schema autodetect

- pipe_tools/io/partitionedsink.py
- tests/test_datepartitionedsink.py
> Fix for multiple shards in PartitionedFileWriter

- CHANGES.md
- pipe_tools/__init__.py
> Release 0.1.1

- pipe_tools/options/__init__.py
- pipe_tools/options/actions.py
- pipe_tools/options/logging_options.py
- pipe_tools/options/validate.py
- pipe_tools/utils/__init__.py
- pipe_tools/utils/flatten.py
- pipe_tools/utils/uuid.py
- tests/test_options.py
- tests/test_utils.py
Close #14
Close #15 
Close #17
> Logging support, cli improvements and uuid

- pipe_tools/io/partitionedsink.py
- tests/test_keypartitionedsink.py
> Fix #18 Writing 0 records with PartitionedFileSink fails

- CHANGES.md
- pipe_tools/__init__.py
- setup.py
> Release 0.1.2

- pipe_tools/timestamp.py
- pipe_tools/utils/timestamp.py
- setup.py
- tests/test_timestamp.py
- tests/test_utils.py
> Bugfix for as_timestamp()

- CHANGES.md
- pipe_tools/__init__.py
> Release v0.1.3

- pipe_tools/io/gcp/__init__.py
- pipe_tools/io/gcp/gcpsink.py
- pipe_tools/io/gcp/gcpsource.py
- pipe_tools/io/gcp/util.py
- setup.py
Migrate the universal GCP source and sink from pipe_segment
> Add GCP source and sink

- CHANGES.md
- pipe_tools/__init__.py
Closes #29 
#27 Add GCP source and sink
#31 Tools for airflow
> Release v0.1.4

- pipe_tools/airflow/dataflow_operator.py
- setup.py
- tests/test_airflow.py
> Automatically set pool based on the runner in  DataFlowDirectRunnerOperator

- bin/pipe-tools-utils
- bin/xdaterange
- setup.py
Bash utility scripts available on pip install
* pipe-tools-utils
* xdaterange
> Add some utility bash scripts

- pipe_tools/airflow/models.py
- setup.py
- tests/conftest.py
- tests/test_airflow.py
Add a DagFactory to the airflow toolset taht encapsulates some more of the common Dag initialization functionality for GFW mini-pipelines
> DagFactory

- CHANGES.md
- pipe_tools/__init__.py
Closes #35 
#34 Automatically set pool based on the runner in DataFlowDirectRunnerOperator 
#36 Utility bash scripts - xdaterange
#37 DagFactory
> Release v0.1.5 

- pipe_tools/airflow/operators/bigquery_operator.py
Related with> https://github.com/GlobalFishingWatch/GFW-Tasks/issues/945
> Suppors partitioned and non-partitioned tables

- pipe_tools/__init__.py
- setup.py
This is a hotfix.
There will be added to support branch and tag with hotfix tag.
Related with> https://github.com/GlobalFishingWatch/gfw-eng-tasks/issues/27
> Pins ujson==1.35 and set HOTFIX version.

- setup.py
Related with> https://github.com/GlobalFishingWatch/gfw-eng-tasks/issues/27
> Pins ujson to version 1.35

- Dockerfile
- pickle-json-perf-test.py
- pipe_tools/cookbook/automation/copyfile.py
- pipe_tools/cookbook/normalize/normalize.py
- pipe_tools/cookbook/normalize/shipdataprocess.py
- pipe_tools/cookbook/pipeline_options.py
- pipe_tools/cookbook/read_bigquery.py
- pipe_tools/cookbook/read_write_bigquery.py
- pipe_tools/cookbook/schema_autodetect.py
- pipe_tools/cookbook/write_bq_date_partitions.py
- pipe_tools/cookbook/write_date_partitions.py
- pipe_tools/io/bqdatepartitionedsink.py
- pipe_tools/io/partitionedsink.py
- pipe_tools/options/logging_options.py
- pipe_tools/utils/uuid.py
- tests/test_io_gcp.py
- tests/test_timestamp.py
Related with> https://github.com/GlobalFishingWatch/gfw-eng-tasks/issues/41
> Includes support for python 3.7

- pipe_tools/beam/requirements.py
Related with> https://github.com/GlobalFishingWatch/gfw-eng-tasks/issues/110
> Pin the rsa version to 4.0

- CHANGES.md
- README.md
- pipe_tools/__init__.py
- pipe_tools/beam/requirements.py
- pipe_tools/cookbook/automation/package.json
- setup.py
Related with> https://globalfishingwatch.atlassian.net/browse/PIPELINE-84
> Adds support for Apache Beam 2.28.0
